[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openai_forward"
description = "ðŸš€ Openai api forward Â· OpenAI æŽ¥å£è½¬å‘æœåŠ¡ Â· streaming forward"
authors = [
    { name = "kunyuan", email = "beidongjiedeguang@gmail.com" },
]
requires-python = ">=3.6"
readme = "README.md"
keywords = ["openai", "chatgpt", "openai-api", "openai-proxy", "forward", "streaming-api", "fastapi", "python"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3"
]

dependencies = [
    "loguru",
    "sparrow-python>=0.1.1",
    "fastapi",
    "uvicorn",
    "orjson",
    "python-dotenv",
    "httpx",
]

dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/beidongjiedeguang/openai-forward"
Documentation = "https://github.com/beidongjiedeguang/openai-forward#openai-forward"
Issues = "https://github.com/beidongjiedeguang/openai-forward/issues"
Source = "https://github.com/beidongjiedeguang/openai-forward"

[project.optional-dependencies]
ssl = [
    "certbot"
]
chatgpt = [
    "revChatGPT",
]
bard = [
    "GoogleBard",
]
edge = [
    "EdgeGPT",
]

[project.scripts]
openai_forward = "openai_forward.__main__:main"
openai-forward = "openai_forward.__main__:main"
aifwd = "openai_forward.__main__:main"

[tool.hatch.version]
path = "openai_forward/__init__.py"

[tool.isort]
profile = "black"

[tool.hatch.build]
include = [
    "openai_forward/**/*.py",
]
exclude = [
]

artifacts = [
    "openai_forward/web/index.js",
]


[tool.hatch.build.targets.wheel]
packages = ["openai_forward"]